# Generated by Django 5.1 on 2024-08-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_officer',
            field=models.BooleanField(default=False),
        ),
    ]
