# Generated by Django 5.1 on 2024-09-05 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_passportapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passportapplication',
            name='citizenship_proof_type',
        ),
        migrations.RemoveField(
            model_name='passportapplication',
            name='country_of_birth_parent',
        ),
    ]
