# Generated by Django 5.1 on 2024-09-05 14:11

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_passportapplication_place_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='passportapplication',
            name='country_of_birth_parent',
            field=django_countries.fields.CountryField(default='Zambia', max_length=2),
        ),
        migrations.AddField(
            model_name='passportapplication',
            name='place_of_birth',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='passportapplication',
            name='age_at_last_birthday',
            field=models.IntegerField(default=16),
        ),
        migrations.AlterField(
            model_name='passportapplication',
            name='color_of_eyes',
            field=models.CharField(default='Black', max_length=50),
        ),
        migrations.AlterField(
            model_name='passportapplication',
            name='color_of_hair',
            field=models.CharField(default='Black', max_length=50),
        ),
        migrations.AlterField(
            model_name='passportapplication',
            name='country_of_birth',
            field=django_countries.fields.CountryField(default='Zambia', max_length=2),
        ),
        migrations.AlterField(
            model_name='passportapplication',
            name='height',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='passportapplication',
            name='national_status_of_parent',
            field=django_countries.fields.CountryField(default='Zambia', max_length=2),
        ),
        migrations.AlterField(
            model_name='passportapplication',
            name='other_names',
            field=models.CharField(default='hey', max_length=200),
        ),
        migrations.AlterField(
            model_name='passportapplication',
            name='passport_type',
            field=models.CharField(choices=[('ordinary_32', 'Ordinary 32 pages'), ('ordinary_48', 'Ordinary 48 pages'), ('diplomatic', 'Diplomatic')], default='Ordinary 32 pages', max_length=20),
        ),
        migrations.AlterField(
            model_name='passportapplication',
            name='personal_address',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='passportapplication',
            name='place_of_birth_parent',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='passportapplication',
            name='profession_or_occupation',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='passportapplication',
            name='reason_for_passport',
            field=models.CharField(choices=[('new', 'New Passport'), ('renewal', 'Renewal'), ('lost', 'Lost Passport')], default='New Passport', max_length=20),
        ),
        migrations.AlterField(
            model_name='passportapplication',
            name='residence_country',
            field=django_countries.fields.CountryField(default='Zambia', max_length=2),
        ),
        migrations.AlterField(
            model_name='passportapplication',
            name='service_type',
            field=models.CharField(choices=[('express', 'Express'), ('live_photo', 'Live Photograph')], default='Express', max_length=20),
        ),
        migrations.AlterField(
            model_name='passportapplication',
            name='surname',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='passportapplication',
            name='usual_place_of_residence',
            field=models.CharField(default='lusaka', max_length=255),
        ),
    ]
